modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Matyrobbrt/UltimateResourceGenerators/issues" #optional
[[mods]] #mandatory
modId="urg" #mandatory
version="${version}" #mandatory
displayName="UltimateResourceGenerators" #mandatory
#updateJSONURL="https://raw.githubusercontent.com/Matyrobbrt/MatyLib/1.16.5/versions_forge_system.json" #optional
#displayURL="https://www.curseforge.com/minecraft/mc-mods/matylib" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Matyrobbrt" #optional
description='''
A mod that adds custom resource generators. Inspired by USRG, this mod gives more flexibility and functionality to pack makers.
'''
[[dependencies.urg]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.urg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.urg]]
    modId="matylib"
    mandatory=true
    versionRange="[1.0.4,)"
    ordering="NONE"
    side="BOTH"

